service: onica-serverless-api

plugins:
  - serverless-webpack
  - serverless-plugin-log-retention
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  tableThroughputs:
    prod: "5"
    default: "1"
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  logRetentionInDays: 30

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2

  environment:
    tableName:
      Ref: IdsTable

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - Fn::GetAtt:
            - IdsTable
            - Arn

functions:
  list:
    handler: src/list.main
    events:
      - http:
          path: id
          method: get
          cors: true

  get:
    handler: src/get.main
    events:
      - http:
          path: id/{id}
          method: get
          cors: true

resources:
  # Dynamodb
  - ${file(resources/dynamodb-table.yml)}
