AWSTemplateFormatVersion: "2010-09-09"
Description: "CI/CD pipelines for serverless api"

Resources:
  SLSCodeCommit:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: serverless-api

Outputs:
  HttpURL:
    Value:
      Fn::GetAtt:
        - SLSCodeCommit
        - CloneUrlHttp
  SSHURL:
    Value:
      Fn::GetAtt:
        - SLSCodeCommit
        - CloneUrlSsh
