AWSTemplateFormatVersion: "2010-09-09"
Description: "CI/CD pipelines for serverless api"

Resources:
  SLSCodeCommit:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: serverless-api

  SLSDevCICDArtifactStoreBucket:
    Type: AWS::S3::Bucket

  SLSProdCICDArtifactStoreBucket:
    Type: AWS::S3::Bucket

  SLSCodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: sls-codepipline-service-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Resource: "*"
                Effect: Allow
              - Action:
                  - s3:PutObject
                Resource:
                  # bucket arn is prefixed with cf stack name sls-pipeline
                  - arn:aws:s3:::sls-pipeline*
                Effect: Allow
              - Action:
                  - codecommit:CancelUploadArchive
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:UploadArchive
                Resource:
                  - Fn::GetAtt:
                      - SLSCodeCommit
                      - Arn
                Effect: Allow
              - Action:
                  - cloudwatch:*
                  - iam:PassRole
                Resource: "*"
                Effect: Allow
              - Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource: "*"
                Effect: Allow

  SLSCodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: sls-codebuild-service-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - logs:*
                Resource: "*"
                Effect: Allow
              - Action:
                  - dynamodb:BatchWriteItem
                  - dynamodb:DescribeTable
                  - dynamodb:CreateTable
                Resource:
                  - arn:aws:dynamodb:us-west-2:873340800138:table/dev-ids*
                  - arn:aws:dynamodb:us-west-2:873340800138:table/prod-ids
                Effect: Allow
              - Action:
                  - cloudformation:Describe*
                  - cloudformation:List*
                  - cloudformation:Get*
                  - cloudformation:PreviewStackUpdate
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                Resource:
                  - arn:aws:cloudformation:us-west-2:873340800138:stack/onica-serverless-api-dev*/*
                  - arn:aws:cloudformation:us-west-2:873340800138:stack/onica-serverless-api-prod*/*
                Effect: Allow
              - Action:
                  - cloudformation:ValidateTemplate
                Resource: "*"
                Effect: Allow
              - Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:Get*
                  - s3:List*
                Resource: arn:aws:s3:::*
                Effect: Allow
              - Action:
                  - s3:*
                Resource: arn:aws:s3:::*/*
                Effect: Allow
              - Action:
                  - iam:GetRole
                  - iam:PassRole
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                  - iam:AttachRolePolicy
                  - iam:DeleteRolePolicy
                Resource:
                  - arn:aws:iam::873340800138:role/onica-serverless-api-dev*-lambdaRole
                  - arn:aws:iam::873340800138:role/onica-serverless-api-prod*-lambdaRole
                Effect: Allow
              - Action:
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:DELETE
                Resource:
                  - arn:aws:apigateway:us-west-2::/restapis
                Effect: Allow
              - Action:
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:DELETE
                Resource:
                  - arn:aws:apigateway:us-west-2::/restapis/*
                Effect: Allow
              - Action:
                  - lambda:GetFunction
                  - lambda:CreateFunction
                  - lambda:DeleteFunction
                  - lambda:UpdateFunctionConfiguration
                  - lambda:UpdateFunctionCode
                  - lambda:ListVersionsByFunction
                  - lambda:PublishVersion
                  - lambda:CreateAlias
                  - lambda:DeleteAlias
                  - lambda:UpdateAlias
                  - lambda:GetFunctionConfiguration
                  - lambda:AddPermission
                  - lambda:RemovePermission
                  - lambda:InvokeFunction
                Resource:
                  - arn:aws:lambda:*:873340800138:function:onica-serverless-api-dev*
                  - arn:aws:lambda:*:873340800138:function:onica-serverless-api-prod*
                Effect: Allow
              - Action:
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcs
                Resource:
                  - "*"
                Effect: Allow
              - Action:
                  - events:Put*
                  - events:Remove*
                  - events:Delete*
                  - events:Describe*
                Resource:
                  - arn:aws:events::873340800138:rule/onica-serverless-api-dev*
                  - arn:aws:events::873340800138:rule/onica-serverless-api-prod*
                Effect: Allow

  DevCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: onica-serverless-api-dev
      ServiceRole:
        Ref: SLSCodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:8.11.0
        EnvironmentVariables:
          - Name: STAGE
            Value: dev
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10

  DevCodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/codebuild/"
            - Ref: DevCodeBuild

  SLSDevCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        Fn::GetAtt:
          - SLSCodePipelineServiceRole
          - Arn
      ArtifactStore:
        Location:
          Ref: SLSDevCICDArtifactStoreBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName:
                  Fn::GetAtt:
                    - SLSCodeCommit
                    - Name
                BranchName: dev
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: DevBuild
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName:
                  Ref: DevCodeBuild

  ProdCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: onica-serverless-api-prod
      ServiceRole:
        Ref: SLSCodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:8.11.0
        EnvironmentVariables:
          - Name: STAGE
            Value: prod
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10

  ProdCodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/codebuild/"
            - Ref: ProdCodeBuild

  SLSProdAppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        Fn::GetAtt:
          - SLSCodePipelineServiceRole
          - Arn
      ArtifactStore:
        Location:
          Ref: SLSProdCICDArtifactStoreBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName:
                  Fn::GetAtt:
                    - SLSCodeCommit
                    - Name
                BranchName: master
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: ProdBuild
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName:
                  Ref: ProdCodeBuild

Outputs:
  HttpURL:
    Value:
      Fn::GetAtt:
        - SLSCodeCommit
        - CloneUrlHttp
  SSHURL:
    Value:
      Fn::GetAtt:
        - SLSCodeCommit
        - CloneUrlSsh
